---

name: Merge

on:
  push:
    branches:
      - main

jobs:
  gettext:
    name: Gettext
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/elementary/flatpak-platform/runtime:8-x86_64
      options: --privileged

    steps:
    - name: Update Translation Files
      uses: elementary/actions/gettext-flatpak@main
      with:
        manifest-path: 'io.github.ellie_commons.jorts.yml'
